logging:
  level:
    root: INFO
    org.springframework.cache: TRACE
spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        generate_statistics: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
          hazelcast.instance_name: hazelcastInstance
      javax.persistence.sharedCache.mode: ENABLE_SELECTIVE
tsm:
  sticky: false
  hazelcast.instance.name: hazelcastInstance
