INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME, BIRTHDATE) VALUES (1, 'John', 'Doe', '1970-01-01');
INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME, BIRTHDATE) VALUES (2, 'Jane', 'Doe', '1972-02-02');
INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME, BIRTHDATE) VALUES (3, 'John', 'Roe', '1974-03-03');